version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    command: [--auth]
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: checkit
